### ISSUE TITLE
Consider changing name to `react-native-honeybadger`

### ISSUE THREAD

**Issue by jamonholmgren** [honeybadger-io/honeybadger-react-native#13]
This is a minor thing, and you can feel free to ignore.

If you do a search on NPM for `react-native`, you'll notice that the majority of libraries are named `react-native-*`.

https://www.npmjs.com/search?q=react-native

Renaming to `react-native-honeybadger` would align with that emergent convention.

Feel free to close with `wontfix` as well. Won't hurt my feelings. :grinning:

**Comment by joshuap** [comment]
Thanks for the suggestion! I'm going to close this one because we're using an NPM organization, so the actual package name is `@honeybadger-io/react-native`. The GitHub repo is named `honeybadger-*` is just an internal naming convention we use.
