### ISSUE TITLE
Hermes regular expression

### ISSUE THREAD

**Issue by braccolucianoj** [honeybadger-io/honeybadger-react-native#14]
Hello there, the issue is related to the regular expression used to transform the stack into the array of frames in an Android environment using Hermes. It doesn't support **named capture groups** so the code doesn't work for Android. 

Could someone give me some help to give support for this feature without using this kind of regular expressions? (at least as a temporary fix) 
[Link to Hermes regular expressions features](https://hermesengine.dev/docs/regexp)

**Comment by andreybutov** [comment]
@braccolucianoj Hi. Thanks for the feedback. Let me take a look and I'll push out a patch.

**Comment by braccolucianoj** [comment]
> @braccolucianoj Hi. Thanks for the feedback. Let me take a look and I'll push out a patch.

Thanks!

**Comment by andreybutov** [comment]
@braccolucianoj Hi. Could you let me know the steps you took where you encountered the error? I'm having trouble getting this to fail with Hermes enabled.

**Comment by braccolucianoj** [comment]
> @braccolucianoj Hi. Could you let me know the steps you took where you encountered the error? I'm having trouble getting this to fail with Hermes enabled.

So, in order to make it fail:
1. I simply added the honeybadger library 
2. I configure it on the root application's file (App.js)
3. I throw a random error inside a useEffect: `throw new Error('testing')`. (It's done after calling the configure method)

In other environments (different from dev) it breaks on the build process pointing to the same error: `Invalid regular expression: Quantifier has nothing to repeat`

**Comment by andreybutov** [comment]
@braccolucianoj This has been patched. You can grab version 0.0.5 from npm. Thanks so much for the bug report!
