### ISSUE TITLE
Add revision and projectRoot options

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-react-native#4]
We need the ability to configure these two options to enable additional features for source maps:

- [`notice.server.revision`](https://github.com/honeybadger-io/honeybadger-schemas/blob/master/exceptions/v1/notices.json#L355)
- [`notice.server.project_root`](https://github.com/honeybadger-io/honeybadger-schemas/blob/master/exceptions/v1/notices.json#L335)

The configuration options should be named `revision` and `projectRoot`, and should be configured like this:

```js
Honeybadger.configure({
  apiKey: "Your Honeybadger API key",
  revision: "Current GIT SHA",
  projectRoot: "/private/var/containers/Bundle/Application"
});
```

## Resources

- [Client Library Spec - Configuration Options](https://www.notion.so/honeybadger/Client-Library-Spec-aa891332f7874196aa0695b6d38dca66#f17617aeac3d4a1aa0cb17bcd68341d0)
- [honeybadger.js Configuration Options](https://docs.honeybadger.io/lib/javascript/reference/configuration.html#configuration-options)
- [Notice Payload Schema](https://github.com/honeybadger-io/honeybadger-schemas/blob/master/exceptions/v1/notices.json#L335)

**Comment by andreybutov** [comment]
This is done in 9b88b12

**Comment by joshuap** [comment]
Thanks! I updated the changelog: https://github.com/honeybadger-io/honeybadger-react-native/commit/274ae8d2b028db49a5296024fffd1cc05ba84657
