### ISSUE TITLE
Reduce default console logging

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-react-native#5]
Background:

> I see some console logs in both the case of error (honeybadger-react-native: The native module was not found. Please review the installation instructions.) but also for some standard operations (Setting up the JavaScript global error handler.). **I would avoid console logging unconditionally if not in an error situation.** In small amounts it likely isn't a problem but console.logs in a production RN app is considered bad practice as it can slow down the JS engine while interpreting your code. Typically you would want to allow the user to configure this with something like a log level.

I think adding a log level option is a good idea. The default could then be `"warning"`.

**Comment by andreybutov** [comment]
@joshuap Is there a log level API that's already implemented in a HB client lib somewhere that would be a good example of how that should look like to the client code?

**Comment by andreybutov** [comment]
This is resolved in eb73e086441c0e5837ba3464813fb673681fbf72
