### ISSUE TITLE
Display RedBoxes for debugging

### ISSUE THREAD

**Issue by joshuap** [honeybadger-io/honeybadger-react-native#9]
Background:

> When honeybadger is configured you don't get redboxes which would be inconvenient for a developer. The reason for this is the global error handler that RN uses isn't called here https://github.com/honeybadger-io/honeybadger-react-native/blob/c52cb2612d81e7be412859af901a6f7ce53df93d/index.js#L141 I think.

![2021-04-28 21 41 23](https://user-images.githubusercontent.com/474649/118016871-c9b41800-b30a-11eb-8bd3-49a3f12e760f.gif)

See also: https://archive.reactnative.dev/docs/debugging#in-app-errors-and-warnings

**Comment by andreybutov** [comment]
This is resolved in 3b56cfacd7306a5820e2cb29397b7367422e1191
